let leagues = [
    'Grand Master', 
    'Master 1', 
    'Diamond 1', 
    'Diamond 2', 
    'Diamond 3',
    'Diamond 4', 
    'Diamond 5', 
    'Diamond 6',
    'Diamond 7',
    'Platinum 1', 
    'Platinum 2', 
    'Platinum 3',
    'Platinum 4', 
    'Platinum 5', 
    'Platinum 6',
    'Platinum 7',
    'Gold 1', 
    'Gold 2', 
    'Gold 3',
    'Gold 4', 
    'Gold 5', 
    'Gold 6',
    'Gold 7',
    'Silver 1', 
    'Silver 2', 
    'Silver 3',
    'Silver 4', 
    'Silver 5', 
    'Silver 6',
    'Silver 7',
    'Bronze 1', 
    'Bronze 2', 
    'Bronze 3',
    'Bronze 4', 
    'Bronze 5', 
    'Bronze 6',
    'Bronze 7'
]

module.exports = leagues;